#modLoader = "javafml"
#loaderVersion = "[43,)"

modLoader="kotlinforforge"
loaderVersion="[3,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "discholder"
version = "${version}"
displayName = "Kenza's Disc Holder and DJ"
authors = "Kenza"
description = '''
Add disc holders and Dj villager to the game.
'''
#logoFile = ""

[[dependencies.discholder]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.discholder]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.discholder]]
modId = "architectury"
mandatory = true
versionRange = "[7.0.66,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.discholder]]
modId="libgui"
mandatory=true
versionRange="[6.5.1,)"
ordering="NONE"
side="BOTH"