modLoader = "javafml"
loaderVersion = "[40,)"

#modLoader="kotlinforforge"
#loaderVersion="[3,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "discholder"
version = "${version}"
displayName = "Kenza's Disc Holder and DJ"
authors = "Kenza"
description = '''
Add disc holders and Dj villager to the game.
'''
#logoFile = ""

[[dependencies.discholder]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.discholder]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.discholder]]
modId = "architectury"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"